# platform :ios, '15.0'

target 'DemoUIKit' do
  use_frameworks!

  # source 'git@github.com:infinitech-dev/LinkAttribution-SwiftSDK.git'
  pod 'LinkAttribution', :path => '../' do |p|
    p.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
  end

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      # Disable sandbox for framework copying
      config.build_settings['ENABLE_APP_SANDBOX'] = 'NO'
      config.build_settings['ENABLE_USER_SCRIPT_SANDBOXING'] = 'NO'
      # Additional settings that might help
      config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
      config.build_settings['CODE_SIGNING_REQUIRED'] = 'NO'
    end
  end
end
