# platform :ios, '15.0'

workspace 'Polar_ObjCDemo'

target 'ObjcDemo' do
  use_frameworks!

  # source 'git@github.com:infinitech-dev/LinkAttribution-SwiftSDK.git'
#  pod 'PolarGX', :path => '../' do |p|
#    p.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
#  end

#  pod 'PolarGX', :git => 'git@github.com:infinitech-dev/LinkAttribution-SwiftSDK.git', :branch => 'main'


end

#post_install do |installer|
#  installer.pods_project.targets.each do |target|
#    target.build_configurations.each do |config|
#      # Comprehensive sandbox disabling
#      config.build_settings['ENABLE_APP_SANDBOX'] = 'NO'
#      config.build_settings['ENABLE_USER_SCRIPT_SANDBOXING'] = 'NO'
#      config.build_settings['SYSTEM_FRAMEWORK_SEARCH_PATHS'] = '$(inherited) $(PLATFORM_DIR)/Developer/Library/Frameworks'
#      config.build_settings['ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES'] = 'YES'
#      # Skip sandboxing for user scripts
#      config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
#      config.build_settings['CODE_SIGNING_REQUIRED'] = 'NO'
#    end
#  end
#end
