# platform :ios, '15.0'

workspace 'Polar_ObjCDemo'

target 'ObjcDemo' do
  use_frameworks!

  # source 'git@github.com:infinitech-dev/LinkAttribution-SwiftSDK.git'
  pod 'PolarGX', :path => '../'

end
